### ISSUE TITLE
Neo 好像有人冒充你给我们公司卖了500个账号，我和反馈以及您确认下，谢谢

### ISSUE THREAD

**Issue by flyer1995onsky** [pengzhile/atlassian-helper#19]
大神好，事情是这样的，我们公司通过供应商，购买了 chat.zhiliao.io  500个账号，但是体验非常卡，很不好，我想确认下，是不是是有人在你网站注册了账号，冒称是您的工作人员，向我们售卖？还是确实是您知情的，感谢。我不大会用github，如果留言就重复了，表示抱歉

**Comment by pengzhile** [comment]
重复问题，已在另一个issue回复。
