### ISSUE TITLE
大神，你好！

### ISSUE THREAD

**Issue by LHCBYT** [pengzhile/atlassian-helper#3]
看到你的博客感觉style很cool，所以请问你的博客页面是否有模板或者是否有使用了什么ui组件，希望可以告知下！

**Comment by pengzhile** [comment]
> 看到你的博客感觉style很cool，所以请问你的博客页面是否有模板或者是否有使用了什么ui组件，希望可以告知下！

不是什么大神。用的Hexo静态博客，NexT主题。

**Comment by LHCBYT** [comment]
@pengzhile 谢谢答复！
