### ISSUE TITLE
大佬, 那个ide reset不见了,我想上车

### ISSUE THREAD

**Issue by Weasley-J** [pengzhile/atlassian-helper#4]
`大佬, 那个ide reset不见了,我想上车`

**Comment by pengzhile** [comment]
https://gitee.com/pengzhile/ide-eval-resetter

**Comment by Weasley-J** [comment]
### 谢谢啊, 我又找到组织了,跟丢两次了

**Comment by ysctest** [comment]
@pengzhile 关于大佬在公众号提出的 问题，我现在有几个点需要确认一下，百分比是   {0.00} 这种格式还是  {1.11%}这种格式亦或者  {百分之二十} 这种格式。md5 加密是用的 16位 还是 32 位 以及是大写 或者小写

**Comment by pengzhile** [comment]
> @pengzhile 关于大佬在公众号提出的 问题，我现在有几个点需要确认一下，百分比是 {0.00} 这种格式还是 {1.11%}这种格式亦或者 {百分之二十} 这种格式。md5 加密是用的 16位 还是 32 位 以及是大写 或者小写

0.00 或 0.00%

**Comment by ysctest** [comment]
@pengzhile 方便发下您的邮箱地址么，或者大佬发个邮件到  ysctest@163.com
