### ISSUE TITLE
自定义license 

### ISSUE THREAD

**Issue by NaiHeKK** [pengzhile/atlassian-helper#7]
我想问一下这个自定义license被禁了能不能解开啊？我都不知道咋被封的，我就在公司和自己的笔记本上用过

**Comment by pengzhile** [comment]
没有被封啊。

**Comment by NaiHeKK** [comment]
blocked, this code will be disabled in next agent version.
我打开自定义license界面就显示这个啊

**Comment by NaiHeKK** [comment]
是因为我换了用户名吗

**Comment by NaiHeKK** [comment]
> 没有被封啊。
blocked, this code will be disabled in next agent version.
我打开自定义license界面就显示这个啊
是因为我换了用户名吗

**Comment by NaiHeKK** [comment]
> 没有被封啊。

blocked, this code will be disabled in next agent version.
我打开自定义license界面就显示这个啊
是因为我换了用户名吗

**Comment by pengzhile** [comment]
> > 没有被封啊。
> 
> blocked, this code will be disabled in next agent version.
> 我打开自定义license界面就显示这个啊
> 是因为我换了用户名吗

是的，已解除，再试试。

**Comment by NaiHeKK** [comment]
> > > 没有被封啊。
> > 
> > 
> > blocked, this code will be disabled in next agent version.
> > 我打开自定义license界面就显示这个啊
> > 是因为我换了用户名吗
> 
> 是的，已解除，再试试。

可以了，非常感谢
